Project_1/wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("new_entry", views.new_entry, name="new_entry"),
    path("edit", views.edit, name="edit"),
    path("error", views.error, name="error"),
    path("random_entry", views.random_entry, name="random_entry"),
    path("wiki/<str:title>", views.entry, name="entry"),
]

Project_1/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

Project_1/wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

Project_1/wiki/encyclopedia/views.py
from django import forms
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.urls import reverse

from . import util


def index(request):
	if request.GET.get('q') is not None:
		a_entry = util.get_entry(request.GET.get('q'))
		if a_entry is not None:
			return HttpResponse(entry(request, request.GET.get('q')))
		else:
			entries = util.get_entries(request.GET.get('q'))
			return render(request, "encyclopedia/index.html", {
				"entries": entries,
				"h1": "Search Result",
			})
	else:
	    return render(request, "encyclopedia/index.html", {
	        "entries": util.list_entries(),
	        "h1": "All Pages"
    })

def new_entry(request):
	if request.method == "POST":
		form = NewEntryForm(request.POST)
		if form.is_valid():
			title = form.cleaned_data["title"]
			content = form.cleaned_data["content"]
			if util.get_entry(title) is None:
				util.save_entry(title, content)
				return entry(request, title)
			else:
				return render(request, "encyclopedia/error.html", {
					"msg": f"Entry {title} already exist"
				})
		else:
			return render(request, "encyclopedia/new_entry", {
				"form": form
			})
	else:
		return render(request, "encyclopedia/new_entry.html", {
			"form": NewEntryForm()
		})

def entry(request, title):
	content = util.get_entry(title)
	if content is not None:
		return render(request, "encyclopedia/entry.html", {
			"title": title,
			"content": util.mark2html(content)
		})
	else:
		return render(request, "encyclopedia/error.html", {
			"msg": f"Entry {title} Not Found"
		})

def edit(request):
	if request.method == "POST":
		title = request.POST.get('title')
		content = request.POST.get('content')
		util.save_entry(title, content)
		return entry(request, title)
	else:
		title = request.GET.get('title')
		content = util.get_entry(title)
		return render(request, "encyclopedia/edit.html", {
			"title": title,
			"content": content,
		})

def random_entry(request):
	title = util.get_random()
	return entry(request, title)

def error(request):
	return HttpResponse("Entry No Found")

class NewEntryForm(forms.Form):
	title = forms.CharField(label="Type the Title ")
	content = forms.CharField(widget=forms.Textarea(attrs={'cols': '60', 'rows': '15'}), label="Type the Content ")

Project_1/wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
	Edit Entry
{% endblock %}

{% block body %}
	<h1>Edit a Entry</h1></br>
	<h2>{{ title }}</h2>

    <form action="{% url 'encyclopedia:edit' %}" method="post">
    	{% csrf_token %}
    	<input type="hidden" name="title" value="{{ title }}">
    	<textarea name="content">{{ content }}</textarea>
    	<input type="submit">
    </form>

{% endblock %}

Project_1/wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <!-- <h1>{{ title }}</h1> -->
    {% autoescape off %}
    {{ content }}
    {% endautoescape %}
	</br>
    <a href="{% url 'encyclopedia:edit' %}?title={{ title }}">Edit</a>

{% endblock %}

Project_1/wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h2>{{ msg }}</h2>

{% endblock %}

Project_1/wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>{{ h1 }}</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="/wiki/{{ entry }}"> {{ entry }}</li></a>
        {% endfor %}
    </ul>

{% endblock %}

Project_1/wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:index' %}">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href = "{% url 'encyclopedia:new_entry'%}">Create New Entry</a>
                </div>
                <div>
                    <a href = "{% url 'encyclopedia:random_entry'%}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

Project_1/wiki/encyclopedia/templates/encyclopedia/new_entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
	New Entry
{% endblock %}

{% block body %}
	<h1>Add a New Entry</h1>

    <form action="{% url 'encyclopedia:new_entry' %}" method="post">
    	{% csrf_token %}
    	{{ form }}
    	<input type="submit">
    </form>

{% endblock %}